[workspace]
authors = ["Ikansh Mahajan <ikanshmahajan@gmail.com>"]
channels = ["conda-forge"]
name = "explainable-ai-scene-classification"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
