[workspace]
authors = ["Ikansh Mahajan <ikanshmahajan@gmail.com>"]
channels = ["conda-forge"]
name = "explainable-ai-scene-classification"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
jupyter = ">=1.1.1,<2"
python = "==3.10.6"
numpy = ">=2.2.6,<3"
pandas = ">=2.3.3,<3"
matplotlib = ">=3.10.8,<4"
seaborn = ">=0.13.2,<0.14"

[system-requirements]
# Because of this requirement, pixi will make sure the cuda version of tensorflow is installed.
cuda = "12.0"

[pypi-dependencies]
tensorflow = { version= ">=2.19.1,<3", extras = ["and-cuda"] }
