[workspace]
authors = ["Ikansh Mahajan <ikanshmahajan@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]
license = "MIT"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/ikabrain/explainable-ai-scene-classification/"

[tasks]

[dependencies]
jupyter = ">=1.1.1,<2"
python = "==3.10.6"
numpy = ">=2.2.6,<3"
matplotlib = ">=3.10.8,<4"
seaborn = ">=0.13.2,<0.14"
jupyterlab = ">=4.5.1,<5"
pixi-kernel = ">=0.7.1,<0.8"
jupyterthemes = ">=0.20.0,<0.21"

[system-requirements]
# Because of this requirement, pixi will make sure the cuda version of tensorflow is installed.
cuda = "12.0"

[pypi-dependencies]
tensorflow = { version = ">=2.19.1,<3", extras = ["and-cuda"] }
