[workspace]
authors = ["Ikansh Mahajan <ikanshmahajan@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]
license = "MIT"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/ikabrain/explainable-ai-scene-classification/"

[tasks]

[dependencies]
IPython = ">=8.21.0,<9"
ipykernel = "==6.17.1"
ipywidgets = "==8.0.2"
jupyter_client = "==7.3.4"
jupyter_core = "==5.0.0"
jupyter_server = "==1.23.2"
jupyterlab = "==3.5.0"
nbclient = "==0.7.0"
nbconvert = "==7.2.5"
nbformat = "==5.7.0"
notebook = "==6.5.2"
traitlets = "==5.5.0"
python = "==3.10.6"
numpy = "==1.23.5"
matplotlib = ">=3.10.8,<4"
seaborn = ">=0.13.2,<0.14"
pixi-kernel = "*"
jupyterthemes = "==0.20.0"
scikit-learn = ">=1.7.2,<2"

[system-requirements]
# Because of this requirement, pixi will make sure the cuda version of tensorflow is installed.
cuda = "12"

[pypi-dependencies]
tensorflow = { version = "==2.17.0", extras = ["and-cuda"] }
